### ISSUE TITLE
copy-static.sh issues

### ISSUE THREAD

**Issue by UladBohdan** [babajka/babajka-frontend#8]
`npm install` does not always run `copy-static.sh` although it's in `postinstall`. Some deploy scripts use a workaround running copying manually. Do not know exactly if it fails all the time or fails are conditional. Must be investigated.

**Comment by UladBohdan** [comment]
Permission issues?

```npm WARN lifecycle babajka-frontend@0.0.1~postinstall: cannot run in wd %s %s (wd=%s) babajka-frontend@0.0.1 sh copy-static.sh /root/babajka-deploy/tmp/babajka-frontend```

**Comment by Drapegnik** [comment]
same as when deploying with `now`

**Comment by UladBohdan** [comment]
running `bash copy-static.sh` manually helps

**Comment by UladBohdan** [comment]
Issue seems to be resolved a long time ago.
